version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

jobs:
  eslint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint-fix
          name: Check ESlint

  build-and-push:
    environment:
      DOCKER_IMAGE: tuchan17/my-slack-app
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  deploy: 
    machine:
      image: ubuntu-2004:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ac:7d:dc:82:e4:b6:c8:ef:ef:80:9e:d9:2e:92:e2:0d"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -oStrictHostKeyChecking=no -vv 'tuchanvnu-gitpodtest-hf9oufykvco@tuchanvnu-gitpodtest-hf9oufykvco.ssh.ws-us105.gitpod.io' "./deploy.sh"

workflows:
  test-build-deploy:
    jobs:
      - eslint
      - build-and-push:
          requires:
            - eslint
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - master